### ISSUE TITLE
SpatialLIBD data?

### ISSUE THREAD

**Issue by cnk113** [zijianni/codes_for_SpotClean_paper#1]
Hello,

I noticed that the SpatialLIBD data doesn't provide the necessary files like spot positions, but it seems you do create it in your analysis. I was wondering if you could share the output of your CreateSlide object for the SpatialLIBD datasets?
If it helps, I only need 151507-151510

Best,
Chang

**Comment by zijianni** [comment]
Hi Chang,

You can find imputed SpatialLIBD spot positions under https://uwmadison.box.com/s/oz1g4rcxxtpieht7fel0o6ctetzmbwf3 (SpatialLIBD/12brains.RData). I've also put my imputation code in this repo under SpatialLIBD/spatialLIBD_DE_analysis.Rmd. Note that only background spot positions were imputed here. SpatialLIBD study actually reported their tissue spot positions in their R package. If you don't need background spots, you should directly go with their data.

Let me know if you have further issues with it. 

Best,
Zijian

**Comment by cnk113** [comment]
Thanks for the quick response, just to clarify the raw_matrix is only the background genes? If so could I use the slide_list_imputed values w/ the SpatialLIBD matrix (not just background)?

**Comment by zijianni** [comment]
`raw_matrix` is a list of 12 matrices of raw data, containing all ~35000 genes and 4992 spots. `slide_list` is the slide info I grabbed from the spatialLIBD R package, which only contains tissue spots. `slide_list_impute` contains the slide info of tissue spots (same as in `slide_list`) and imputed background spots. To reproduce the results in our study, it's enough to use `raw_matrix` + `slide_list_impute`.

**Comment by cnk113** [comment]
Again, thanks for the quick response!
